version: '3.7'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      POSTGRES_USER: miyoung
      POSTGRES_PASSWORD: miyoung
      POSTGRES_DB: techeer
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data
  
volumes:
  my_db:
